### ISSUE TITLE
dplyr: namespace ‘Rcpp’ 0.12.14 is being loaded, but >= 0.12.15 is required

### ISSUE THREAD

**Issue by nick-youngblut** [conda-forge/r-dplyr-feedstock#7]
I'm not sure if this is an `r-dplyr` recipe error or something more general, but I thought that it would be best to post it. I currently can't use `r-dplyr=0.7.6` due to a`namespace ‘Rcpp‘` error. The entire issue is reported on [staged-recipes](https://github.com/conda-forge/staged-recipes/issues/6413).

**Comment by jdblischak** [comment]
Closing this now that the Issue was identified in the other thread: https://github.com/conda-forge/staged-recipes/issues/6413#issuecomment-411022636
